[kernel] Do not build xen extension for now, since they fail
  Kernel: arch/x86/boot/bzImage is ready  (#1)
  ERROR: "xen_pcpu_index" [drivers/acpi/processor.ko] undefined!



git-svn-id: https://untangle.svn.beanstalkapp.com/ngfw/kernels@31544 8ebf8b4e-06f3-0310-961f-89f74618be54

Former-commit-id: 9e7da979bd82fb4e8780444d77a6e862ba145b15